# Fish Shell Aliases

alias c="clear"
alias cat="bat"
alias groot="echo 'I am Groot!' && cd (git rev-parse --show-toplevel)"
alias lg="env TMPDIR=/tmp lazygit"
alias nix_rebuild="~/dotfiles/shared/bin/darwin-rebuild-wrapper.sh"
alias nix_update="nix flake update --flake ~/dotfiles/shared/.config/nix-darwin"
alias lazyvim="NVIM_APPNAME=lazyvim command nvim"
alias astrovim="NVIM_APPNAME=astronvim command nvim"
alias wm="workmux"

alias ls="eza"
alias ll="eza -l"
alias la="eza -la"
alias lt="eza --tree"
alias tree="eza --tree"

alias gsb="git-spice branch"
alias gsbc="git-spice branch checkout"
alias gsbcr="git-spice branch create"
alias gsbs="git-spice branch submit"
alias gsbt="git-spice branch track"
alias gsc="git-spice commit"
alias gsca="git-spice commit amend"
alias gscc="git-spice commit commit"
alias gsl="git-spice log long -a"
alias gsll="git-spice log long"
alias gsls="git-spice log short"
alias gsr="git-spice repo"
alias gsrs="git-spice repo sync"
alias gss="git-spice stack"
alias gssr="git-spice stack restack"
alias gsss="git-spice stack submit"
