# Fish Shell Aliases

alias c="clear"
alias cat="bat"
alias groot="echo 'I am Groot!' && cd (git rev-parse --show-toplevel)"
alias lg="env TMPDIR=/tmp lazygit"
alias nix_rebuild="~/dotfiles/shared/bin/darwin-rebuild-wrapper.sh"
alias nix_update="nix flake update --flake ~/dotfiles/shared/.config/nix-darwin"
alias kickstart="command nvim"
alias knvim="command nvim"
alias lazyvim="NVIM_APPNAME=lazyvim command nvim"
alias lvim="NVIM_APPNAME=lazyvim command nvim"
alias vim="NVIM_APPNAME=astronvim command nvim"
alias nvim="NVIM_APPNAME=astronvim command nvim"
alias astrovim="NVIM_APPNAME=astronvim command nvim"
alias avim="NVIM_APPNAME=astronvim command nvim"
alias wm="workmux"

alias ls="eza"
alias ll="eza -l"
alias la="eza -la"
alias lt="eza --tree"
alias tree="eza --tree"

alias gsb="gs branch"
alias gsbc="gs branch checkout"
alias gsbcr="gs branch create"
alias gsbs="gs branch submit"
alias gsbt="gs branch track"
alias gsc="gs commit"
alias gsca="gs commit amend"
alias gscc="gs commit commit"
alias gsl="gs log long -a"
alias gsll="gs log long"
alias gsls="gs log short"
alias gsr="gs repo"
alias gsrs="gs repo sync"
alias gss="gs stack"
alias gssr="gs stack restack"
alias gsss="gs stack submit"
