# Fish Shell Aliases

alias groot="echo 'I am Groot!' && cd (git rev-parse --show-toplevel)"
alias darwin_rebuild="~/dotfiles/shared/bin/darwin-rebuild-wrapper.sh"
alias darwin_update="nix flake update --flake ~/dotfiles/shared/.config/nix-darwin"
alias nix_rebuild="nix profile upgrade personal/.config/nix"
alias nix_update="nix flake update --flake ~/dotfiles/personal/.config/nix && nix profile upgrade personal/.config/nix"
alias lg="env TMPDIR=/tmp lazygit"
alias c="clear"
alias vim="nvim"
alias cat="bat"

alias ls="eza"
alias ll="eza -l"
alias la="eza -la"
alias lt="eza --tree"
alias tree="eza --tree"

alias gsb="gs branch"
alias gsbc="gs branch checkout"
alias gsbcr="gs branch create"
alias gsbs="gs branch submit"
alias gsbt="gs branch track"
alias gsc="gs commit"
alias gsca="gs commit amend"
alias gscc="gs commit commit"
alias gsl="gs log long -a"
alias gsll="gs log long"
alias gsls="gs log short"
alias gsr="gs repo"
alias gsrs="gs repo sync"
alias gss="gs stack"
alias gssr="gs stack restack"
alias gsss="gs stack submit"
