[mgr]
ratio = [2, 3, 5]
show_hidden = true

[flavor]
dark = "catppuccin-mocha"

[opener]
edit = [
  { run = '$EDITOR "$@"', block = false, for = "unix" },
  { run = "%EDITOR% %*",  block = false, for = "windows" },
]
